<?php

return [
    [
        "name" => "Arcanis l'Onnipotente",
        "mana" => 3,
        "thumb" => "https://m.media-amazon.com/images/I/51tfburGhmL._AC_SY355_.jpg",
        "type" => "Creatura Leggendaria - Mago",
        "edition" => "X",
        "first-effect" => "pesca 3 carte",
        "second-effect" => "Fai tornare Arcanis l'Onnipotente in mano al suo proprietario.",
        "third-effect" => "Effetto 3",
        "fourth-effect" => "",
        "description" => "Non preoccuparti della mia origine, della mia razza o del mio lignaggio. Chiedi i miei risultati nell'arena e poi fai la tua scommessa",
        "strength" => 3,
        "constitution" => 4,
    ],
    [
        "name" => "Gianmaria S. il durevole",
        "mana" => 4,
        "thumb" => "https://m.media-amazon.com/images/I/51tfburGhmL._AC_SY355_.jpg",
        "type" => "Creatura Leggendaria - Guerriero",
        "edition" => "X",
        "first-effect" => "tappa 2 carte",
        "second-effect" => "blocca un attacco anche da tappato.",
        "third-effect" => "",
        "fourth-effect" => "",
        "description" => "Si sa poco di questo Guerriero leggendario. Il significato della S. nel suo nome è perso nei tempi. molti sostengono che il suo soprannome sia un dono della sua moglie.",
        "strength" => 2,
        "constitution" => 8,
    ],
    [
        "name" => "Antonio lo sconnessionato",
        "mana" => 2,
        "thumb" => "https://m.media-amazon.com/images/I/51tfburGhmL._AC_SY355_.jpg",
        "type" => "Creatura Leggendaria - Arciere",
        "edition" => "X",
        "first-effect" => "tappa per spaccare una creatura al prossimo turno",
        "second-effect" => "i danni ricevuti vengono calcolati il turno dopo.",
        "third-effect" => "",
        "fourth-effect" => "",
        "description" => "Tutti quelli che lo hanno avvicinato hanno sperimentato un rallento dei movimenti che gli hanno impedito di potersi difendere dai suoi attacchi imprevedibili.",
        "strength" => 6,
        "constitution" => 2,
    ],
];
